server:
  port: 8080
  shutdown: graceful

spring:
  application:
    name: fit-group-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://172.17.0.1:3306/fitGroup?validationQuery="select 1"
    username: fitGroup
    password: fitGroup
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    database: mysql
    open-in-view: false

  kafka:
    consumer:
      bootstrap-servers: 172.17.0.1:9092
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      bootstrap-servers: 172.17.0.1:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

eureka:
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka